include: package:lints/recommended.yaml

# For lint rules and documentation, see https://dart.dev/tools/linter-rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
#   exclude:
#     - path/to/excluded/files/**
